-- AlterTable
ALTER TABLE "public"."attempts" ALTER COLUMN "score" SET DEFAULT 0,
ALTER COLUMN "percentage" SET DEFAULT 0,
ALTER COLUMN "correctAnswers" SET DEFAULT 0,
ALTER COLUMN "incorrectAnswers" SET DEFAULT 0,
ALTER COLUMN "unanswered" SET DEFAULT 0,
ALTER COLUMN "timeTaken" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'IN_PROGRESS',
ALTER COLUMN "startedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "completedAt" DROP NOT NULL;
